[package]
name = "egui_overlay"
version = "0.4.0"
edition = "2021"
license = "MIT"
description = "Egui integration to easily create Desktop Overlays"
repository = "https://github.com/coderedart/egui_overlay.git"

[dependencies]
egui_backend = "0.4"
egui_window_glfw_passthrough = "0.4"
egui_render_three_d = "0.4"
